# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51b60226d648d919a01a6ad7020a980ed55444ce2a7ff7698b4980df7941818e8f605f7d62be917345a6e7766a0ebc80b213f19c57ffd7f44f3ac995abc16b8

test:
  secret_key_base: 5e76ce545f616c15a616aae5c1b478f859086c1438276df4c906ec4b6ece5171e87ba55580594364e18004614e1f4f48b82a24130e1136da1ed801154d64cf70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
